### PR TITLE
MarchingSquares

### PR DESCRIPTION
**Pull request by stebogit**
Hi @tmcw and @morganherlocker,
I implemented the `isobands` function using [`MarchingSquaresJS.js`](https://github.com/RaumZeit/MarchingSquares.js).

I am not sure if it should be still called `isobands`, maybe `contours` would be more appropriate since it outputs a FC of MultiPolygons for a correct visualization on the map.

s.

### CODE REVIEW

**Comment by StefanoGitHub** [comment]
I fixed the issue, ordering the `lineRings` of each `isoband` by their area before creating the `polygon`.
Now it seems to work fine

**Comment by DenisCarriere** [comment]
@StefanoGitHub Great work here, this looks like it fixes a lot of the issues. Unfortunately `turf-isobands` has been worked into [`@turf/isolines`](https://github.com/Turfjs/turf/tree/master/packages/turf-isolines), would you mind sending a new PR to `@turf` instead?

I also agree that the name `isolines` or `isobands` could be renamed as `contours` or `contour`. Maybe in the next **Major** release of Turf `4.x` we can redefine some of the function names.

Ref: https://github.com/Turfjs/turf/issues/390
CC: @tmcw @morganherlocker

**Comment by StefanoGitHub** [comment]
@DenisCarriere, I'll be happy to help.
I haven't worked on this project since I made the PR, so I need to refresh my mind on it. Besides, this is my first time contributing to an OS project and I am not really familiar with PRs. 
Let's see if I've got it right: [`turf-isobands`](https://github.com/Turfjs/turf-isobands/network) is an old separate repo, whose code has been moved to the main repo, `@turf`, which is now divided into folders, one per module. Is that correct?
Do you want me to fork the project ([`master`](https://github.com/Turfjs/turf)) and copy my changes into the [`@turf/turf-isoline`](https://github.com/Turfjs/turf/tree/master/packages/turf-isolines) subfolder, and then make a new PR?

**Comment by DenisCarriere** [comment]
@StefanoGitHub Yes this is exactly what I meant by pushing to `@turf`, I want you to have the credit for these edits when it is merged 👍.

The [`@turf/isolines`](https://github.com/Turfjs/turf/tree/master/packages/turf-isolines) folder should look very similar to your commits, a few tweaks here and there but pretty much the same source code.

**Comment by stebogit** [comment]
@DenisCarriere I am going to work on this this weekend.
Are you sure I should basically override the `isolines` function with the `isobands` one? They are two different functions (the first returning `linestrings`, the second `multipolygons`), I would say probably both worth keeping. Why not just add the `@turf/isobands` folder to the project?

**Comment by DenisCarriere** [comment]
@stebogit that's great news that you will be working on this.

I would stay away from complex GeoJSON geometries such as MultiPolygons, having the final output as LineString would be the ideal scenario. If the user wants to convert those LineStrings into polygons they could use [`turf-line-to-polygon`](https://github.com/Turfjs/turf-line-to-polygon).

If you feel that the `isolines` & `isobands` modules are very different, then feel free to create a new folder for the `isobands` module. However in my opinion these two modules should be merged into one module named `contours`.

**Comment by stebogit** [comment]
In my experience the `isobands` (I'd actually call them contours) need to be MultiPolygons, since it is the best, probably the only, way to correctly identify the area between two, or more likely several, closed lines, i.e. Polygons. Basically they need to be properly nested, so when you feed them to a map, for instance, it is possible to fill and color the enclosed area avoiding wrong "overlapping" of regions. The picture shows you the issue I had with just Polygons.
Also, I believe (not tested) any measurement (e.g. `area`) or function (`inside` is just the first that comes in my mind) over such MultiPolygon `contour` should return a more consistent result.

I agree on a single `contours` module, however I think it would be best having a single function and simply "decompose" the final MultiPolygons into Polygons or even LineStrings if the user needs just that as output, instead of implementing two functions. In the end less code to maintain. 
What do you think?

d1caafc2-3100-11e6-8ffb-2b40bb7f6c74

**Comment by DenisCarriere** [comment]
@stebogit You are correct, it would be really hard to classify and troubleshoot simple polygons vs. multi-polygons. We can start off by having both isolines & isobands as separate modules and we can look at what is the best option for a single `contour` module, I'm guessing if your `isobands` module is fast and accurate we can rename it as contours and have one single module. Having two modules with similar names & similar inputs can be confusing, even for me I get confused and I keep having to reference wikipedia for their differences.

Looking forward to send some tests to your `isobands` module! :+1: 

Will you have an option for precision? Higher precision = higher quality = longer computing time.

**Comment by stebogit** [comment]
I used this [`MarchingSquares`](https://github.com/RaumZeit/MarchingSquares.js) JS implementation, which seems to be the only one available that was not created for computer graphics. I chose this algorithm only because at the time I worked on my contouring map project I read [this interesting article](http://emptypipes.org/2015/07/22/contour-comparison) and thought to try to improve the `isobands` module (cause `turf` is awesome!). I don't know that much about the algorithm though, I just managed to make it work. 😅 
I have no idea how to properly test it in terms of speed or precision... I know it works because I compared the output of my app (on the google map) with the previous tool I replaced.
Do you have any suggestion? 
I found it difficult to test/verify the output without displaying it on a map though.

P.S. I just noticed that Ronny Lorenz's `MarchingSquares` library is licensed under AGPL, is it going to be an issue for `turf`? 😕

**Comment by DenisCarriere** [comment]
@stebogit As for testing, you would simply need to define your `test/in` fixtures with a few example, then after your `test/out` would be autogenerated from your module, once the outputs are generated we can copy-paste them into geojson.io or any other application that can preview GeoJSONs.

You can have a look at the newest module [`@turf/dissolve`](https://github.com/Turfjs/turf/blob/master/packages/turf-dissolve), the output is using `process.env.REGEN` to generate the `test/out`, this seems to be the best way to test those "visual" modules.

As for the AGPL license, I'm not an expert in license compatibilities.

@tmcw Is dependencies using AGPL an issue with Turf?

**Comment by tmcw** [comment]
Unfortunately, from my reading, using AGPL-licensed code _would_ trigger the 'viral' provisions of the license and require that all of Turf be licensed AGPL, and be distributed with its provisions - people couldn't improve Turf and run web services on the improved version, as the current MIT license allows. Under a broad reading, it also requires you have to release any code that even links with or connects to Turf.

It's a bummer, since the implementation is great, but the license is a dealbreaker for inclusion in this project - it'd require we vastly change how Turf is distributed.

**Comment by DenisCarriere** [comment]
@tmcw Sadly I've read the same interpretation of that license. The joys of licensed dependencies... 👎

**Comment by stebogit** [comment]
Hello @DenisCarriere and @tmcw,
I [got in contact](https://github.com/RaumZeit/MarchingSquares.js/issues/3) with the author of the `MarchingSquares` library, who proposed to add in his license:

> [...] an additional clause to the AGPL v3 under Section 7, to allow inclusion of unmodified versions of my library in third-party projects without forcing said third-party project to be subject to any requirement of the AGPL v3.

Would this allow you to merge my changes into Turf?
Thanks

**Comment by DenisCarriere** [comment]
@stebogit Thanks for reaching out to the author, unfortunately I'm also not a license expert, I'll let @tmcw be the judge of that :)

**Comment by morganherlocker** [comment]
If this clause is added, I'm comfortable including the library.

**Comment by stebogit** [comment]
@DenisCarriere thanks for merging my PR, but to be honest MarchingSquareJS has not been modified yet by the author.

**Comment by DenisCarriere** [comment]
Oh, I thought the author said he would...

Well at the moment the the PR is merged, however we didn't publish the library to npm, we can still wait out until the owner adds that comment to his license file.

@stebogit Do you want to port this over to the main TurfJS? We can add it as `@turf/isobands` and eventually when we figure out if we drop `isolines` for `isobands` (or even if we decide to call it `contours`).

**Comment by RaumZeit** [comment]
I will! The addition under Section 7 to my AGPL license will be available tomorrow!

**Comment by stebogit** [comment]
I've already forked and modified the code of `@turf/isobands` as we agreed some time ago (before encountering the license issue); I will create a new PR in there when ready, ok?
(I will be out of town for a couple of weeks bwt, so after my trip)
Thanks again to EVERYBODY for the availability!!

**Comment by DenisCarriere** [comment]
@stebogit Sounds like a plan! I'll help out with a few commits once you have a branch set up.

**Pull request merged**
